name: teste_softdesign
description: A project to a job opportunity of mobile developer with Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+14

environment:
  sdk: '>=3.1.1 <4.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  shimmer_animation: ^2.1.0+1
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.6
  flutter_i18n: ^0.34.0
  flutter_mobx: ^2.1.0
  injectable: ^2.3.1
  equatable: ^2.0.5
  provider: ^6.0.5
  dartz: ^0.10.1
  get_it: ^7.6.4
  crypto: ^3.0.3
  mobx: ^2.2.0
  http: ^1.1.0

dev_dependencies:
  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.3.3
  injectable_generator: ^2.4.0
  flutter_lints: ^2.0.3
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6
  platform: ^3.1.0
  mocktail: ^1.0.1
  mockito: ^5.4.2
  test: ^1.24.3
  file: ^6.1.4

# configuracao da splash
flutter_native_splash:
  color: "#F5F5F5"
  image: assets/img/marvel_logo.png
  android: true
  ios: true
  fullscreen: true

# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/img/
    - assets/languages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
